name: Deploy All PRs

run-name: Deploy All PRs

on:
  push:
    branches: ["main"]

permissions:
  contents: write

concurrency:
  group: "deploy-prs"
  cancel-in-progress: true

jobs:
  getPRs:
    runs-on: ubuntu-latest

    outputs:
      prData: ${{ steps.data.outputs.pullRequestData }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Get PR Data
        id: data
        run: |
          data=$(deno run --allow-net .github/workflows/getPRs.ts ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }}) # output: pullRequestData: {ref: string, number: number}[]
          echo "pullRequestData=$data" >> "$GITHUB_OUTPUT"
          echo "$data"

  build:
    runs-on: ubuntu-latest
    needs: getPRs
    # GH Actions outputs are strings, so we can just compare this to an empty array string. `.length` does not seem to work when parsing the array.
    if: needs.getPRs.outputs.prData != '[]'

    strategy:
      matrix:
        data: ${{ fromJSON(needs.getPRs.outputs.prData) }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.data.ref }}

      - name: Build App
        run: touch .nojekyll  # put any required build scripts here

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.data.number }}
          path: . # replace this with the path to your built code if needed

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download App
        uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: pr

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          target-folder: pr # The folder the action should deploy to.
