name: Deploy All PRs

run-name: Deploy All PRs

on:
  push:
    branches: ["main"]

permissions:
  contents: write

concurrency:
  group: "deploy-prs"
  cancel-in-progress: true

jobs:
  getPRs:
    runs-on: ubuntu-latest

    outputs:
      prData: ${{ steps.data.outputs.pullRequestData }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Get PR Data
        id: data
        run: |
          data=$(deno run --allow-net .github/workflows/getPRs.ts ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }}) # output: pullRequestData: {ref: string, number: number}[]
          echo "pullRequestData=$data" >> "$GITHUB_OUTPUT"
          echo "$data"

  deploy:
    runs-on: ubuntu-latest
    needs: getPRs
    if: fromJson(needs.getPRs.outputs.prData).length != 0

    strategy:
      matrix:
        data: ${{ fromJSON(needs.getPRs.outputs.prData) }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.data.ref }}

      - name: Build App
        run: touch .nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          target-folder: "pr/${{ matrix.data.number }}" # The folder the action should deploy to.
