name: Build

run-name: Build Code

on:
  push:
    branches: ['main']
  schedule:
    - cron: '20 23 28 04 *'

permissions:
  contents: write

concurrency:
  group: 'build'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Do stuff
        run: |
          current=$(date -d "$(date)" +%s)
          dead=$(date -d 2024-04-29 +%s)

          if [ $dead -ge $current ];
          then
              echo "early"
            else
              echo "late"
          fi  